include:
  - project: 'barrierelos/deployment'
    file: '.gitlab-ci-docker-publish-deploy.yml'

default:
  image: node:latest
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline

workflow:
  rules:
    # Prevent creation of duplicate pipelines (https://stackoverflow.com/questions/74114309/avoid-duplicate-ci-pipelines-on-gitlab)
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"

stages:
  - build
  - test
  - publish
  - deploy

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

type-check:
  stage: test
  needs: [ ]
  script:
    - npm run test:typecheck

lint:
  stage: test
  needs: [ ]
  script:
    - npm run test:lint

unit-test:
  stage: test
  needs: [ ]
  script:
    - npm run test:unittest
