include:
  - project: 'barrierelos/deployment'
    file: '.gitlab-ci-docker-publish-deploy.yml'

default:
  image: openjdk:17-jdk-alpine
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - ./gradlew clean

workflow:
  rules:
    # Prevent creation of duplicate pipelines
    # https://stackoverflow.com/a/69860485/3635931
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"

stages:
  - build
  - test
  - publish
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day

check:
  stage: test
  needs: [ ]
  script:
    - ./gradlew check
  coverage: '/    - Line Coverage: ([0-9.]+)%/'
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
