export const Tags = {
  country: {
    switzerland: "country.switzerland",
    liechtenstein: "country.liechtenstein"
  },
  canton: {
    ag: "canton.ag",
    ai: "canton.ai",
    ar: "canton.ar",
    be: "canton.be",
    bl: "canton.bl",
    bs: "canton.bs",
    fr: "canton.fr",
    ge: "canton.ge",
    gl: "canton.gl",
    gr: "canton.gr",
    ju: "canton.ju",
    lu: "canton.lu",
    ne: "canton.ne",
    nw: "canton.nw",
    ow: "canton.ow",
    sg: "canton.sg",
    sh: "canton.sh",
    so: "canton.so",
    sz: "canton.sz",
    tg: "canton.tg",
    ti: "canton.ti",
    ur: "canton.ur",
    vd: "canton.vd",
    vs: "canton.vs",
    zg: "canton.zg",
    zh: "canton.zh",
    fl: "canton.fl",
  }
}
