server:
  port: 8030

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
