server:
  port: 8030

spring:
  datasource:
    url: jdbc:postgresql://localhost:5040/barrierelos?stringtype=unspecified
    username: barrierelos
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://accounts.google.com"
          jwk-set-uri: "https://www.googleapis.com/oauth2/v3/certs"
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
