server:
  port: 8030
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5040/barrierelos?stringtype=unspecified
    username: barrierelos
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://accounts.google.com"
          jwk-set-uri: "https://www.googleapis.com/oauth2/v3/certs"
  rabbitmq:
    host: localhost
    port: 5050
    username: barrierelos
    password: password
    virtual-host: /
  amqp:
    deserialization:
      trust:
        all: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger/index.html
    disable-swagger-default-url: true
    operations-sorter: alpha
    tags-sorter: alpha
