package ch.barrierelos.backend.enums

public enum class CategoryEnum
{
  GOVERNMENT_FEDERAL,
  GOVERNMENT_CANTONAL,
  GOVERNMENT_MUNICIPAL,
  PRIVATE_AFFILIATED,
  PRIVATE_UNIVERSITY,
  PRIVATE_NEWS,
  PRIVATE_SHOP,
  PRIVATE_OTHER
}
