name: Scanner Test Stage

on:
  # push:
  # pull_request:
  workflow_run:
    workflows: 
      - Scanner Build Stage
    types:
      - completed

defaults:
  run:
    working-directory: ./scanner

jobs:
  lint:
    # if: jobs.build.result == 'success'
    runs-on: ubuntu-latest
    # needs: build
    # uses: ./.github/workflows/scanner-build.yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Lint
        run: npm run test:lint

  type-check:
    # if: jobs.build.result == 'success'
    runs-on: ubuntu-latest
    # needs: build
    # uses: ./.github/workflows/scanner-build.yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Type check
        run: npm run test:typecheck

  unit-test:
    # if: jobs.build.result == 'success'
    runs-on: ubuntu-latest
    # needs: build
    # uses: ./.github/workflows/scanner-build.yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Unit test
        run: npm run test:unittest
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/cobertura-coverage.xml


